local base = require('zycore.base')
local goforit = require('zycore.goforit')
local option = require('zycore.option')
local keymap = require('zycore.keymap')
local colorscheme = require('zycore.colorscheme')
local plugin = require('zycore.plugin')
local lsp = require('zycore.lsp')
